---
- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.centos7
    - OULibraries.repox
  tasks:
    - name: packages for development and testing
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - dkms
        - emacs
        - screen
        - net-tools
