---
- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.centos7
    - OULibraries.repox
    - OULibraries.users
  pre_tasks:
    - name: enable selinux for non-vagrant deployments
      selinux:
        state: enforcing
        policy: targeted
      when: environment_name != "vagrant"
  tasks:
    - name: packages for development and testing
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - emacs
        - net-tools
